version: '3.7'
services:
  db-we:
    container_name: db-we
    image: postgres
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - ./docker/pddata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_ROOT_PASSWORD: db_password
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user

volumes:
  fias_spring_database:
